In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("D:\Python programming\Data sets\sales.csv")

In [7]:
df.head(8)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    object
 2   region         500 non-null    object
 3   product        500 non-null    object
 4   category       500 non-null    object
 5   customer_type  500 non-null    object
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), object(5)
memory usage: 39.2+ KB

In [10]:
df.describe()

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

In [13]:
df.rename(columns={"order_id":"order id","customer_type":"customer type"})

,order id,date,region,product,category,customer type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [14]:
df.isnull().sum()

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [15]:
df.groupby("category")["discount"].mean()

category
Accessories    0.151111
Electronics    0.142744
Name: discount, dtype: float64

In [19]:
df.groupby("product")["quantity"].sum().sort_values(ascending=False).head(5)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [20]:
df["date"] = pd.to_datetime(df["date"])

In [22]:
df["month"] = df["date"].dt.month

In [23]:
df.groupby("month")["sales"].sum()

month
1      98673.77
2     131625.24
3      70335.46
4     150967.04
5     176939.29
6     155607.27
7     128419.96
8     194347.39
9     157999.69
10    131809.83
11    118704.40
12    151100.44
Name: sales, dtype: float64

In [24]:
df["discount"].describe()

count    500.00000
mean       0.14666
std        0.08612
min        0.00000
25%        0.08000
50%        0.15000
75%        0.22000
max        0.30000
Name: discount, dtype: float64

In [25]:
df["discount_status"] = np.where(df["discount"] > 0, "With Discount", "No Discount")

df.groupby("discount_status")["sales"].mean()

discount_status
No Discount      4165.846154
With Discount    3310.829117
Name: sales, dtype: float64

In [32]:
df.groupby("product")["sales"].sum().idxmax()

'Laptop'

In [30]:
df.groupby("customer_type")["sales"].mean()

customer_type
New          3321.913640
Returning    3343.265977
Name: sales, dtype: float64